"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const item_controller_1 = require("../controllers/item.controller");
const itemRouter = (0, express_1.Router)();
itemRouter.get("/getAll", item_controller_1.getAllItems);
itemRouter.get("/getById/:id", item_controller_1.getItemsById);
itemRouter.post("/save", item_controller_1.saveItem);
itemRouter.put("/update/:id", item_controller_1.updateItem);
itemRouter.delete("/delete/:id", item_controller_1.deleteItem);
exports.default = itemRouter;
